# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               모험으로 사는 인생
tagline:             "L'Aventure de la Vie"
description:         '<a href="http://litiblue.com" target="_blank">litiblue</a> </br> Twitter : <a href="https://twitter.com/litiblue" target="_blank">@litiblue</a>'
url:                 http://www.litiblue.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Steve Seo
  url:               https://twitter.com/litiblue
  email:             litiblue@gmail.com

# Custom vars
version:             1.0.0

gems:
  - jekyll-paginate
